# General Client ID's
CLIENT_GO_GET_LOST = 4
CLIENT_OBJECT_UPDATE_FIELD = 24
CLIENT_OBJECT_UPDATE_FIELD_RESP = 24
CLIENT_CREATE_OBJECT_REQUIRED_RESP = 34
CLIENT_DISCONNECT = 37
CLIENT_DONE_INTEREST_RESP = 48
CLIENT_HEARTBEAT = 52
CLIENT_ADD_INTEREST = 97
CLIENT_LOGIN_3 = 111
CLIENT_LOGIN_3_RESP = 110